I = imread('Test.jpeg');
subplot(2,2,1);
imshow(I);title('Original Image');
H = fspecial('prewitt');
MotionBlur = imfilter(I,H,'replicate');
subplot(2,2,2);
imshow(MotionBlur);title('Prewitt Image');
H = fspecial('sobel');
MotionBlur = imfilter(I,H,'replicate');
subplot(2,2,3);
imshow(MotionBlur);title('Sobel Image');
H = fspecial('Laplacian',0.2);
MotionBlur = imfilter(I,H,'replicate');
subplot(2,2,4);
imshow(MotionBlur);title('Laplacian Image');